// convex/map/zones/boardwalk.ts
// Zone 12: Boardwalk (6800,2000 → 7800,4600)
// 1000×2600 — Luxury oceanfront strip. Hotels, casino, resort amenities.

import type { ZoneData } from "./types";

const boardwalk: ZoneData = {
  id: "boardwalk",
  buildings: [
    {
      name: "Luxury Hotel A",
      category: "commercial",
      subType: "luxury_hotel",
      x: 7000,
      y: 2200,
      width: 100,
      height: 80,
      maxOwners: 20,
      basePrice: 15000,
      baseIncome: 400,
      notes: "5-star hotel, penthouse suites",
    },
    {
      name: "Luxury Hotel B",
      category: "commercial",
      subType: "luxury_hotel",
      x: 7000,
      y: 2700,
      width: 100,
      height: 80,
      maxOwners: 20,
      basePrice: 15000,
      baseIncome: 400,
      notes: "Oceanview rooms",
    },
    {
      name: "Boardwalk Casino",
      category: "commercial",
      subType: "casino",
      x: 7000,
      y: 3200,
      width: 120,
      height: 80,
      maxOwners: 25,
      basePrice: 20000,
      baseIncome: 500,
      notes: "Mini-games, slots",
    },
    {
      name: "Resort Pool",
      category: "service",
      subType: "resort_pool",
      x: 7050,
      y: 3700,
      width: 80,
      height: 60,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Pool area, relaxation buff",
    },
    {
      name: "Arcade",
      category: "commercial",
      subType: "arcade",
      x: 7050,
      y: 4100,
      width: 60,
      height: 50,
      maxOwners: 15,
      basePrice: 8000,
      baseIncome: 180,
      notes: "Games, prizes, fun",
    },
    {
      name: "Ice Cream Stand",
      category: "shop",
      subType: "ice_cream_stand",
      x: 7300,
      y: 2500,
      width: 30,
      height: 20,
      maxOwners: 5,
      basePrice: 2000,
      baseIncome: 50,
      notes: "Treats, seasonal flavors",
    },
    {
      name: "Yacht Club Shop",
      category: "shop",
      subType: "yacht_club_shop",
      x: 7300,
      y: 4400,
      width: 60,
      height: 40,
      maxOwners: 10,
      basePrice: 10000,
      baseIncome: 220,
      notes: "Nautical gear, memberships",
    },
  ],
  roads: [
    {
      name: "Boardwalk Main",
      x1: 6900,
      y1: 2000,
      x2: 6900,
      y2: 4600,
      style: "boardwalk",
    },
    {
      name: "Boardwalk Promenade",
      x1: 7500,
      y1: 2000,
      x2: 7500,
      y2: 4600,
      style: "boardwalk",
    },
    {
      name: "Boardwalk North Cross",
      x1: 6900,
      y1: 2000,
      x2: 7500,
      y2: 2000,
      style: "boardwalk",
    },
    {
      name: "Boardwalk South Cross",
      x1: 6900,
      y1: 4600,
      x2: 7500,
      y2: 4600,
      style: "boardwalk",
    },
  ],
  decorations: [
    {
      name: "Ferris Wheel",
      type: "ferris_wheel",
      x: 7600,
      y: 3200,
      width: 80,
      height: 80,
    },
    {
      name: "Boardwalk Lamps N",
      type: "lamp_row",
      x: 6900,
      y: 2300,
      width: 10,
      height: 200,
    },
    {
      name: "Boardwalk Lamps S",
      type: "lamp_row",
      x: 6900,
      y: 3800,
      width: 10,
      height: 200,
    },
  ],
};

export default boardwalk;
