// convex/map/zones/boardwalk.ts
// Zone 12: Boardwalk & Resort (2200,6800 → 6000,7600)
// 3800×800 — Wide beachfront entertainment strip at the south of the island.

import type { ZoneData } from "./types";

const boardwalk: ZoneData = {
  id: "boardwalk",
  buildings: [
    {
      name: "Luxury Hotel A",
      category: "commercial",
      subType: "luxury_hotel",
      x: 2400,
      y: 6900,
      width: 100,
      height: 80,
      maxOwners: 20,
      basePrice: 15000,
      baseIncome: 400,
      notes: "5-star hotel, penthouse suites",
    },
    {
      name: "Luxury Hotel B",
      category: "commercial",
      subType: "luxury_hotel",
      x: 2900,
      y: 6900,
      width: 100,
      height: 80,
      maxOwners: 20,
      basePrice: 15000,
      baseIncome: 400,
      notes: "Oceanview rooms",
    },
    {
      name: "Boardwalk Casino",
      category: "commercial",
      subType: "casino",
      x: 3500,
      y: 6900,
      width: 120,
      height: 80,
      maxOwners: 25,
      basePrice: 20000,
      baseIncome: 500,
      notes: "Mini-games, slots",
    },
    {
      name: "Resort Pool",
      category: "service",
      subType: "resort_pool",
      x: 4100,
      y: 6920,
      width: 80,
      height: 60,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Pool area, relaxation buff",
    },
    {
      name: "Arcade",
      category: "commercial",
      subType: "arcade",
      x: 4600,
      y: 6920,
      width: 60,
      height: 50,
      maxOwners: 15,
      basePrice: 8000,
      baseIncome: 180,
      notes: "Games, prizes, fun",
    },
    {
      name: "Ice Cream Stand",
      category: "shop",
      subType: "ice_cream_stand",
      x: 5100,
      y: 7200,
      width: 30,
      height: 20,
      maxOwners: 5,
      basePrice: 2000,
      baseIncome: 50,
      notes: "Treats, seasonal flavors",
    },
    {
      name: "Yacht Club Shop",
      category: "shop",
      subType: "yacht_club_shop",
      x: 5500,
      y: 7200,
      width: 60,
      height: 40,
      maxOwners: 10,
      basePrice: 10000,
      baseIncome: 220,
      notes: "Nautical gear, memberships",
    },
  ],
  roads: [
    {
      name: "Boardwalk Main",
      x1: 2300,
      y1: 6850,
      x2: 5900,
      y2: 6850,
      style: "boardwalk",
    },
    {
      name: "Boardwalk Promenade",
      x1: 2300,
      y1: 7400,
      x2: 5900,
      y2: 7400,
      style: "boardwalk",
    },
  ],
  decorations: [
    {
      name: "Ferris Wheel",
      type: "ferris_wheel",
      x: 5700,
      y: 7050,
      width: 80,
      height: 80,
    },
    {
      name: "Boardwalk Lamps N",
      type: "lamp_row",
      x: 3000,
      y: 6850,
      width: 10,
      height: 200,
    },
    {
      name: "Boardwalk Lamps S",
      type: "lamp_row",
      x: 4500,
      y: 6850,
      width: 10,
      height: 200,
    },
  ],
};

export default boardwalk;
