// convex/map/zones/commercial.ts
// Zone 8: Commercial Strip (3400,4200 → 5400,5400)
// 2000×1200 — Dense retail connector between Downtown, Suburbs, Industrial, and Farmland.

import type { ZoneData } from "./types";

const commercial: ZoneData = {
  id: "commercial",
  buildings: [
    // ── Market Boulevard (north row) ──
    {
      name: "Farmer's Market",
      category: "shop",
      subType: "farmers_market",
      x: 3500,
      y: 4350,
      width: 80,
      height: 60,
      maxOwners: 15,
      basePrice: 5000,
      baseIncome: 100,
      notes: "Sell crops, buy produce",
    },
    {
      name: "Electronics Store",
      category: "shop",
      subType: "electronics_store",
      x: 3900,
      y: 4350,
      width: 60,
      height: 50,
      maxOwners: 10,
      basePrice: 6000,
      baseIncome: 120,
      notes: "Gadgets, phones",
    },
    {
      name: "Mega Mart",
      category: "shop",
      subType: "mega_mart",
      x: 4200,
      y: 4350,
      width: 100,
      height: 70,
      maxOwners: 20,
      basePrice: 8000,
      baseIncome: 200,
      notes: "General store, wide selection",
    },
    {
      name: "Furniture Outlet",
      category: "shop",
      subType: "furniture_outlet",
      x: 4700,
      y: 4350,
      width: 80,
      height: 60,
      maxOwners: 10,
      basePrice: 7000,
      baseIncome: 150,
      notes: "Buy furniture (crafted from wood)",
    },
    {
      name: "Auto Parts",
      category: "shop",
      subType: "auto_parts",
      x: 5100,
      y: 4350,
      width: 50,
      height: 40,
      maxOwners: 10,
      basePrice: 4000,
      baseIncome: 80,
      notes: "Vehicle parts, tools",
    },

    // ── Trade Road (south row) ──
    {
      name: "Pet Shop",
      category: "shop",
      subType: "pet_shop",
      x: 3500,
      y: 4950,
      width: 50,
      height: 40,
      maxOwners: 10,
      basePrice: 3000,
      baseIncome: 60,
      notes: "Pets, animal supplies",
    },
    {
      name: "Wholesale Depot",
      category: "commercial",
      subType: "wholesale",
      x: 3800,
      y: 4950,
      width: 120,
      height: 80,
      maxOwners: 15,
      basePrice: 10000,
      baseIncome: 250,
      notes: "Bulk goods, supply chain hub",
    },
    {
      name: "Sports Store",
      category: "shop",
      subType: "sports_store",
      x: 4400,
      y: 4950,
      width: 60,
      height: 50,
      maxOwners: 10,
      basePrice: 5000,
      baseIncome: 100,
      notes: "Equipment, camping gear",
    },
    {
      name: "Pharmacy",
      category: "shop",
      subType: "pharmacy",
      x: 4800,
      y: 4950,
      width: 50,
      height: 40,
      maxOwners: 10,
      basePrice: 4000,
      baseIncome: 80,
      notes: "Medicine, health items",
    },
    {
      name: "Bank Branch",
      category: "service",
      subType: "bank_branch",
      x: 5100,
      y: 4950,
      width: 50,
      height: 40,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Satellite bank, basic transactions",
    },
  ],
  roads: [
    {
      name: "Market Boulevard",
      x1: 3400,
      y1: 4300,
      x2: 5400,
      y2: 4300,
      style: "boulevard",
    },
    {
      name: "Trade Road",
      x1: 3400,
      y1: 4900,
      x2: 5400,
      y2: 4900,
      style: "boulevard",
    },
    {
      name: "Center Drive",
      x1: 4400,
      y1: 4300,
      x2: 4400,
      y2: 4900,
      style: "boulevard",
    },
  ],
  decorations: [],
};

export default commercial;
