// convex/map/zones/downtown.ts
// Zone 5: Downtown (4000,2800 → 6400,4800)
// 2400×2000 — Dense urban core with skyscrapers, corporate offices, and financial services.

import type { ZoneData } from "./types";

const downtown: ZoneData = {
  id: "downtown",
  buildings: [
    // ── Service Buildings ──
    {
      name: "City Hall",
      category: "service",
      subType: "city_hall",
      x: 4600,
      y: 3000,
      width: 120,
      height: 100,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Mayor office, permits, court, main quests",
    },
    {
      name: "Bank Tower",
      category: "service",
      subType: "bank_tower",
      x: 4300,
      y: 3000,
      width: 80,
      height: 100,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Deposits, withdrawals, loans, interest",
    },
    {
      name: "Stock Exchange",
      category: "service",
      subType: "stock_exchange",
      x: 5100,
      y: 3600,
      width: 100,
      height: 80,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Future: invest in businesses, trade shares",
    },
    {
      name: "Casino",
      category: "service",
      subType: "casino",
      x: 5000,
      y: 4100,
      width: 140,
      height: 100,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Gambling mini-games, shows, bar",
    },
    {
      name: "Police HQ",
      category: "service",
      subType: "police_hq",
      x: 5900,
      y: 4100,
      width: 100,
      height: 80,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Report crimes, pay fines, bounty board",
    },

    // ── Commercial ──
    {
      name: "Mega Mall",
      category: "commercial",
      subType: "mega_mall",
      x: 4100,
      y: 4050,
      width: 160,
      height: 120,
      maxOwners: 50,
      basePrice: 15000,
      baseIncome: 400,
      notes: "Multiple shops inside, cinema",
    },
    {
      name: "Plaza Hotel",
      category: "commercial",
      subType: "plaza_hotel",
      x: 5800,
      y: 3050,
      width: 120,
      height: 80,
      maxOwners: 20,
      basePrice: 12000,
      baseIncome: 300,
      notes: "Lodging, event venue",
    },
    {
      name: "Investment Firm",
      category: "commercial",
      subType: "investment_firm",
      x: 5300,
      y: 3050,
      width: 60,
      height: 50,
      maxOwners: 10,
      basePrice: 10000,
      baseIncome: 250,
      notes: "Financial services",
    },
    {
      name: "Law Office",
      category: "commercial",
      subType: "law_office",
      x: 4100,
      y: 3600,
      width: 50,
      height: 40,
      maxOwners: 10,
      basePrice: 8000,
      baseIncome: 200,
      notes: "Legal services",
    },
    {
      name: "Insurance Co.",
      category: "commercial",
      subType: "insurance",
      x: 5500,
      y: 3600,
      width: 60,
      height: 50,
      maxOwners: 10,
      basePrice: 8000,
      baseIncome: 200,
      notes: "Insurance products",
    },
    {
      name: "News Tower",
      category: "commercial",
      subType: "news_tower",
      x: 5900,
      y: 3600,
      width: 50,
      height: 60,
      maxOwners: 10,
      basePrice: 7000,
      baseIncome: 180,
      notes: "Media, information",
    },
    {
      name: "Office Tower",
      category: "commercial",
      subType: "office_tower",
      x: 4500,
      y: 4750,
      width: 80,
      height: 80,
      maxOwners: 15,
      basePrice: 8000,
      baseIncome: 200,
      notes: "Corporate offices",
    },
    {
      name: "Tech Hub",
      category: "commercial",
      subType: "tech_hub",
      x: 4100,
      y: 4750,
      width: 60,
      height: 50,
      maxOwners: 10,
      basePrice: 9000,
      baseIncome: 220,
      notes: "Startup space, tech jobs",
    },

    // ── Residential ──
    {
      name: "Luxury Apartment",
      category: "residential",
      subType: "luxury_apartment",
      x: 4100,
      y: 3050,
      width: 80,
      height: 70,
      maxOwners: 20,
      basePrice: 10000,
      baseIncome: 200,
      notes: "High-end housing",
    },
    {
      name: "Condo Tower",
      category: "residential",
      subType: "condo_tower",
      x: 5500,
      y: 4750,
      width: 80,
      height: 70,
      maxOwners: 20,
      basePrice: 7000,
      baseIncome: 150,
      notes: "Mid-tier housing",
    },

    // ── Shops ──
    {
      name: "Food Court",
      category: "shop",
      subType: "food_court",
      x: 4500,
      y: 4100,
      width: 60,
      height: 50,
      maxOwners: 15,
      basePrice: 5000,
      baseIncome: 100,
      notes: "Multiple food vendors",
    },
    {
      name: "Clothing Store",
      category: "shop",
      subType: "clothing_store",
      x: 5600,
      y: 4100,
      width: 60,
      height: 50,
      maxOwners: 15,
      basePrice: 5000,
      baseIncome: 120,
      notes: "Fashion, cosmetics",
    },
    {
      name: "Coffee Shop",
      category: "shop",
      subType: "coffee_shop",
      x: 4900,
      y: 4750,
      width: 30,
      height: 30,
      maxOwners: 10,
      basePrice: 3000,
      baseIncome: 60,
      notes: "Quick food, +energy buff",
    },
    {
      name: "Gym",
      category: "shop",
      subType: "gym",
      x: 5900,
      y: 4750,
      width: 40,
      height: 40,
      maxOwners: 10,
      basePrice: 4000,
      baseIncome: 80,
      notes: "Fitness, +stamina buff",
    },
  ],
  roads: [
    {
      name: "Boulevard North",
      x1: 4000,
      y1: 2900,
      x2: 6400,
      y2: 2900,
      style: "boulevard",
    },
    {
      name: "Financial District",
      x1: 4000,
      y1: 3500,
      x2: 6400,
      y2: 3500,
      style: "boulevard",
    },
    {
      name: "Main Avenue",
      x1: 4000,
      y1: 3950,
      x2: 6400,
      y2: 3950,
      style: "boulevard",
    },
    {
      name: "South Boulevard",
      x1: 4000,
      y1: 4650,
      x2: 6400,
      y2: 4650,
      style: "boulevard",
    },
    {
      name: "West Boulevard",
      x1: 4000,
      y1: 2800,
      x2: 4000,
      y2: 4800,
      style: "boulevard",
    },
    {
      name: "East Boulevard",
      x1: 6400,
      y1: 2800,
      x2: 6400,
      y2: 4800,
      style: "boulevard",
    },
    {
      name: "Central N-S",
      x1: 5200,
      y1: 2800,
      x2: 5200,
      y2: 4800,
      style: "boulevard",
    },
  ],
  decorations: [],
};

export default downtown;
