// convex/map/zones/farmland.ts
// Zone 9: Farmland (600,5400 → 3800,7000)
// 3200×1600 — Rolling fields with crop plots, barns, livestock pens, and a farmer's market.

import type { ZoneData } from "./types";

const farmland: ZoneData = {
  id: "farmland",
  buildings: [
    {
      name: "Farmhouse #1",
      category: "residential",
      subType: "farmhouse",
      x: 700,
      y: 5600,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1500,
      baseIncome: 20,
      notes: "Farmer's home",
    },
    {
      name: "Farmhouse #2",
      category: "residential",
      subType: "farmhouse",
      x: 3400,
      y: 6800,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1500,
      baseIncome: 20,
      notes: "Farmer's home",
    },
    {
      name: "Barn A",
      category: "commercial",
      subType: "barn",
      x: 700,
      y: 6150,
      width: 80,
      height: 60,
      maxOwners: 10,
      basePrice: 4000,
      baseIncome: 80,
      notes: "Animal storage, milk/eggs",
    },
    {
      name: "Barn B",
      category: "commercial",
      subType: "barn",
      x: 3200,
      y: 6150,
      width: 80,
      height: 60,
      maxOwners: 10,
      basePrice: 4000,
      baseIncome: 80,
      notes: "Hay, tool storage",
    },
    {
      name: "Seed & Feed Store",
      category: "shop",
      subType: "seed_store",
      x: 3200,
      y: 5650,
      width: 60,
      height: 50,
      maxOwners: 10,
      basePrice: 3000,
      baseIncome: 60,
      notes: "Seeds, fertilizer, animal feed",
    },
    {
      name: "Farmhouse Kitchen",
      category: "shop",
      subType: "farmhouse_kitchen",
      x: 1400,
      y: 6750,
      width: 100,
      height: 70,
      maxOwners: 15,
      basePrice: 6000,
      baseIncome: 120,
      notes: "Cook raw produce, sell meals",
    },
    {
      name: "Farmhouse #3",
      category: "residential",
      subType: "farmhouse",
      x: 2200,
      y: 5600,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1500,
      baseIncome: 20,
      notes: "Farmer's home",
    },
  ],
  roads: [
    {
      name: "Farm Road North",
      x1: 600,
      y1: 5500,
      x2: 3800,
      y2: 5500,
      style: "gravel",
    },
    {
      name: "Farm Road Mid",
      x1: 600,
      y1: 6000,
      x2: 3800,
      y2: 6000,
      style: "gravel",
    },
    {
      name: "Farm Road South",
      x1: 600,
      y1: 6600,
      x2: 3800,
      y2: 6600,
      style: "gravel",
    },
    {
      name: "Farm Center Lane",
      x1: 2200,
      y1: 5500,
      x2: 2200,
      y2: 6600,
      style: "gravel",
    },
  ],
  decorations: [
    {
      name: "Windmill",
      type: "windmill",
      x: 2600,
      y: 6750,
      width: 40,
      height: 40,
    },
  ],
};

export default farmland;
