// convex/map/zones/forest.ts
// Zone 1: Forest (600,600 → 3400,3000)
// 2800×2400 — Dense woodland with trails, lumber camps, and a central sawmill.

import type { ZoneData } from "./types";

const forest: ZoneData = {
  id: "forest",
  buildings: [
    {
      name: "Ranger Station",
      category: "service",
      subType: "ranger_station",
      x: 700,
      y: 800,
      width: 60,
      height: 50,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Axe vendor, quest board, trail map",
    },
    {
      name: "Sawmill",
      category: "service",
      subType: "quarry",
      x: 1400,
      y: 2150,
      width: 120,
      height: 80,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Wood → Planks processing, sell wood",
    },
    {
      name: "Lumber Camp A",
      category: "commercial",
      subType: "warehouse",
      x: 1300,
      y: 1200,
      width: 40,
      height: 40,
      maxOwners: 5,
      basePrice: 2000,
      baseIncome: 40,
      notes: "North-west camp, axe required",
    },
    {
      name: "Lumber Camp B",
      category: "commercial",
      subType: "warehouse",
      x: 900,
      y: 1600,
      width: 40,
      height: 40,
      maxOwners: 5,
      basePrice: 2000,
      baseIncome: 40,
      notes: "West camp",
    },
    {
      name: "Lumber Camp C",
      category: "commercial",
      subType: "warehouse",
      x: 2800,
      y: 1900,
      width: 40,
      height: 40,
      maxOwners: 5,
      basePrice: 2000,
      baseIncome: 40,
      notes: "East camp, near mountains",
    },
    {
      name: "Lumber Camp D",
      category: "commercial",
      subType: "warehouse",
      x: 1000,
      y: 2650,
      width: 40,
      height: 40,
      maxOwners: 5,
      basePrice: 2000,
      baseIncome: 40,
      notes: "South camp",
    },
  ],
  roads: [
    {
      name: "North Trail",
      x1: 1000,
      y1: 1000,
      x2: 2600,
      y2: 1000,
      style: "trail",
    },
    {
      name: "North Trail (south leg)",
      x1: 2600,
      y1: 1000,
      x2: 2600,
      y2: 2000,
      style: "trail",
    },
    {
      name: "Central Trail",
      x1: 1000,
      y1: 2000,
      x2: 2600,
      y2: 2000,
      style: "trail",
    },
    {
      name: "South Trail",
      x1: 2200,
      y1: 2600,
      x2: 2600,
      y2: 2600,
      style: "trail",
    },
    {
      name: "West Connector",
      x1: 1000,
      y1: 1000,
      x2: 1000,
      y2: 2600,
      style: "trail",
    },
  ],
  decorations: [
    {
      name: "North Trail Gate",
      type: "gate",
      x: 1000,
      y: 650,
      width: 20,
      height: 20,
    },
    {
      name: "South Trail Gate",
      type: "gate",
      x: 2200,
      y: 2950,
      width: 20,
      height: 20,
    },
  ],
};

export default forest;
