// convex/map/zones/harbor.ts
// Zone 4: Harbor (6400,2600 → 7600,4600)
// 1200×2000 — Bustling port with docks, a fish market, and shipping warehouses.

import type { ZoneData } from "./types";

const harbor: ZoneData = {
  id: "harbor",
  buildings: [
    {
      name: "Harbor Master",
      category: "service",
      subType: "harbor_master",
      x: 6500,
      y: 2800,
      width: 60,
      height: 50,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Shipping quests, port authority",
    },
    {
      name: "Customs House",
      category: "service",
      subType: "customs_house",
      x: 6800,
      y: 2800,
      width: 80,
      height: 60,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Import/export, trade licenses",
    },
    {
      name: "Lighthouse",
      category: "service",
      subType: "lighthouse",
      x: 7200,
      y: 2900,
      width: 40,
      height: 80,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Landmark, visible across map",
    },
    {
      name: "Dry Dock",
      category: "service",
      subType: "dry_dock",
      x: 6500,
      y: 4400,
      width: 100,
      height: 70,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Boat repair, future boat purchase",
    },
    {
      name: "Boat Rental",
      category: "service",
      subType: "boat_rental",
      x: 7000,
      y: 4400,
      width: 50,
      height: 40,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Rent boats for island/fishing",
    },
    {
      name: "Fish Market",
      category: "shop",
      subType: "fish_market",
      x: 6500,
      y: 3350,
      width: 100,
      height: 60,
      maxOwners: 15,
      basePrice: 8000,
      baseIncome: 160,
      notes: "Sell fish, buy seafood",
    },
    {
      name: "Ship Supply",
      category: "shop",
      subType: "ship_supply",
      x: 6900,
      y: 3350,
      width: 60,
      height: 50,
      maxOwners: 10,
      basePrice: 5000,
      baseIncome: 100,
      notes: "Rope, nets, fishing rods, bait",
    },
    {
      name: "Bait Shop",
      category: "shop",
      subType: "bait_shop",
      x: 7200,
      y: 3500,
      width: 30,
      height: 30,
      maxOwners: 8,
      basePrice: 2000,
      baseIncome: 40,
      notes: "Bait, lures (on the pier)",
    },
    {
      name: "Warehouse A",
      category: "commercial",
      subType: "warehouse",
      x: 6500,
      y: 3950,
      width: 80,
      height: 60,
      maxOwners: 10,
      basePrice: 6000,
      baseIncome: 150,
      notes: "Storage, shipping goods",
    },
    {
      name: "Warehouse B",
      category: "commercial",
      subType: "warehouse",
      x: 6900,
      y: 3950,
      width: 80,
      height: 60,
      maxOwners: 10,
      basePrice: 6000,
      baseIncome: 150,
      notes: "Storage, bulk cargo",
    },
    {
      name: "Cold Storage",
      category: "commercial",
      subType: "warehouse",
      x: 7200,
      y: 3950,
      width: 60,
      height: 50,
      maxOwners: 10,
      basePrice: 7000,
      baseIncome: 170,
      notes: "Refrigerated fish/food storage",
    },
  ],
  roads: [
    {
      name: "Dock Road",
      x1: 6400,
      y1: 3150,
      x2: 7200,
      y2: 3150,
      style: "dock",
    },
    {
      name: "Warehouse Row",
      x1: 6400,
      y1: 3850,
      x2: 7200,
      y2: 3850,
      style: "dock",
    },
    {
      name: "Main Dock",
      x1: 6400,
      y1: 2600,
      x2: 6400,
      y2: 4600,
      style: "dock",
    },
  ],
  decorations: [],
};

export default harbor;
