// convex/map/zones/industrial.ts
// Zone 10: Industrial (4600,4600 → 6800,6600)
// 2200×2000 — Factories, warehouses, and processing plants. The crafting hub.

import type { ZoneData } from "./types";

const industrial: ZoneData = {
  id: "industrial",
  buildings: [
    // ── Factory Row North ──
    {
      name: "Sawmill Factory",
      category: "commercial",
      subType: "sawmill_factory",
      x: 4700,
      y: 4800,
      width: 140,
      height: 100,
      maxOwners: 25,
      basePrice: 12000,
      baseIncome: 350,
      notes: "Wood → Planks → Furniture",
    },
    {
      name: "Smelter & Forge",
      category: "commercial",
      subType: "smelter",
      x: 5100,
      y: 4800,
      width: 120,
      height: 100,
      maxOwners: 25,
      basePrice: 14000,
      baseIncome: 380,
      notes: "Ore → Ingots → Tools",
    },
    {
      name: "Food Processing",
      category: "commercial",
      subType: "food_processing",
      x: 5500,
      y: 4800,
      width: 140,
      height: 100,
      maxOwners: 25,
      basePrice: 12000,
      baseIncome: 350,
      notes: "Crops/Fish → Meals/Sushi",
    },
    {
      name: "Chemical Plant",
      category: "commercial",
      subType: "chemical_plant",
      x: 6200,
      y: 4800,
      width: 100,
      height: 80,
      maxOwners: 20,
      basePrice: 10000,
      baseIncome: 300,
      notes: "Herbs → Potions/Medicine",
    },

    // ── Logistics Avenue (warehouses) ──
    {
      name: "Warehouse C",
      category: "commercial",
      subType: "warehouse",
      x: 4700,
      y: 5450,
      width: 80,
      height: 60,
      maxOwners: 10,
      basePrice: 6000,
      baseIncome: 150,
      notes: "General storage",
    },
    {
      name: "Warehouse D",
      category: "commercial",
      subType: "warehouse",
      x: 5000,
      y: 5450,
      width: 80,
      height: 60,
      maxOwners: 10,
      basePrice: 6000,
      baseIncome: 150,
      notes: "Raw materials depot",
    },
    {
      name: "Warehouse E",
      category: "commercial",
      subType: "warehouse",
      x: 5300,
      y: 5450,
      width: 80,
      height: 60,
      maxOwners: 10,
      basePrice: 6000,
      baseIncome: 150,
      notes: "Finished goods",
    },
    {
      name: "Warehouse F",
      category: "commercial",
      subType: "warehouse",
      x: 5600,
      y: 5450,
      width: 80,
      height: 60,
      maxOwners: 10,
      basePrice: 7000,
      baseIncome: 170,
      notes: "Cold storage",
    },
    {
      name: "Shipping Hub",
      category: "service",
      subType: "shipping_hub",
      x: 6000,
      y: 5450,
      width: 120,
      height: 80,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Central dispatch, delivery bonuses",
    },

    // ── Industrial South ──
    {
      name: "Textile Mill",
      category: "commercial",
      subType: "textile_mill",
      x: 4700,
      y: 6050,
      width: 120,
      height: 80,
      maxOwners: 20,
      basePrice: 10000,
      baseIncome: 280,
      notes: "Wool → Cloth → Clothing",
    },
    {
      name: "Electronics Factory",
      category: "commercial",
      subType: "electronics_factory",
      x: 5200,
      y: 6050,
      width: 120,
      height: 100,
      maxOwners: 25,
      basePrice: 15000,
      baseIncome: 400,
      notes: "Ore → Circuits → Gadgets",
    },
    {
      name: "Recycling Center",
      category: "service",
      subType: "recycling",
      x: 5700,
      y: 6050,
      width: 80,
      height: 60,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Salvage items, reclaim materials",
    },
    {
      name: "Power Station",
      category: "service",
      subType: "power_station",
      x: 6100,
      y: 6050,
      width: 100,
      height: 80,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Landmark, zone power source",
    },
  ],
  roads: [
    {
      name: "Factory Row North",
      x1: 4600,
      y1: 4750,
      x2: 6800,
      y2: 4750,
      style: "industrial",
    },
    {
      name: "Logistics Avenue",
      x1: 4600,
      y1: 5350,
      x2: 6800,
      y2: 5350,
      style: "industrial",
    },
    {
      name: "Industrial South",
      x1: 4600,
      y1: 5950,
      x2: 6800,
      y2: 5950,
      style: "industrial",
    },
    {
      name: "Central Corridor",
      x1: 5700,
      y1: 4750,
      x2: 5700,
      y2: 5950,
      style: "industrial",
    },
  ],
  decorations: [],
};

export default industrial;
