// convex/map/zones/mountains.ts
// Zone 2: Mountains (2800,400 → 5600,2200)
// 2800×1800 — Rocky highlands with mining sites, switchback trails, and a quarry.

import type { ZoneData } from "./types";

const mountains: ZoneData = {
  id: "mountains",
  buildings: [
    {
      name: "Lookout North",
      category: "service",
      subType: "lookout",
      x: 3800,
      y: 600,
      width: 30,
      height: 30,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Scenic view, binoculars",
    },
    {
      name: "Lookout East",
      category: "service",
      subType: "lookout",
      x: 5200,
      y: 1500,
      width: 30,
      height: 30,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Scenic view, telescope",
    },
    {
      name: "Mine A",
      category: "commercial",
      subType: "warehouse",
      x: 4000,
      y: 1050,
      width: 50,
      height: 50,
      maxOwners: 8,
      basePrice: 5000,
      baseIncome: 100,
      notes: "Iron ore + copper",
    },
    {
      name: "Mine B",
      category: "commercial",
      subType: "warehouse",
      x: 4800,
      y: 2050,
      width: 50,
      height: 50,
      maxOwners: 8,
      basePrice: 8000,
      baseIncome: 150,
      notes: "Gold ore + gems",
    },
    {
      name: "Quarry",
      category: "service",
      subType: "quarry",
      x: 3800,
      y: 1700,
      width: 160,
      height: 100,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Stone extraction, ore processing",
    },
    {
      name: "Mountain Lodge",
      category: "service",
      subType: "mountain_lodge",
      x: 3400,
      y: 2050,
      width: 80,
      height: 60,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Rest stop, supplies, quest board",
    },
  ],
  roads: [
    {
      name: "Ridge Trail (horizontal)",
      x1: 3400,
      y1: 950,
      x2: 5200,
      y2: 950,
      style: "trail",
    },
    {
      name: "Ridge Trail (south)",
      x1: 5200,
      y1: 950,
      x2: 5200,
      y2: 1500,
      style: "trail",
    },
    {
      name: "West Switchback",
      x1: 3000,
      y1: 1000,
      x2: 3000,
      y2: 2100,
      style: "trail",
    },
    {
      name: "Quarry Access",
      x1: 3400,
      y1: 1700,
      x2: 4200,
      y2: 1700,
      style: "trail",
    },
  ],
  decorations: [],
};

export default mountains;
