// convex/map/zones/oldtown.ts
// Zone 3: Old Town (5000,1400 → 6800,3600)
// 1800×2200 — Historic district with narrow streets, a town square, and traditional shops.

import type { ZoneData } from "./types";

const oldtown: ZoneData = {
  id: "oldtown",
  buildings: [
    {
      name: "Museum",
      category: "service",
      subType: "museum",
      x: 6200,
      y: 1600,
      width: 100,
      height: 80,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "History exhibits, quest NPCs",
    },
    {
      name: "Town Hall",
      category: "service",
      subType: "town_hall",
      x: 5600,
      y: 2150,
      width: 100,
      height: 80,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Admin, permits, town quests",
    },
    {
      name: "Clock Tower",
      category: "service",
      subType: "clock_tower",
      x: 6400,
      y: 2200,
      width: 40,
      height: 60,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Landmark, visible from afar",
    },
    {
      name: "Antique Shop",
      category: "shop",
      subType: "antique_shop",
      x: 5100,
      y: 1600,
      width: 60,
      height: 50,
      maxOwners: 10,
      basePrice: 6000,
      baseIncome: 120,
      notes: "Rare items, collectibles",
    },
    {
      name: "Bakery",
      category: "shop",
      subType: "bakery",
      x: 5400,
      y: 1600,
      width: 50,
      height: 40,
      maxOwners: 10,
      basePrice: 4000,
      baseIncome: 80,
      notes: "Unique food (bread, pastry)",
    },
    {
      name: "Tailor",
      category: "shop",
      subType: "tailor",
      x: 6000,
      y: 1600,
      width: 50,
      height: 50,
      maxOwners: 10,
      basePrice: 5000,
      baseIncome: 100,
      notes: "Cosmetics, old-style clothing",
    },
    {
      name: "Herb Shop",
      category: "shop",
      subType: "herbalist",
      x: 5100,
      y: 2200,
      width: 40,
      height: 40,
      maxOwners: 10,
      basePrice: 3500,
      baseIncome: 70,
      notes: "Crafting herbs, potions",
    },
    {
      name: "Bookstore",
      category: "shop",
      subType: "bookstore",
      x: 6000,
      y: 2200,
      width: 40,
      height: 50,
      maxOwners: 10,
      basePrice: 3000,
      baseIncome: 60,
      notes: "Lore books, skill manuals",
    },
    {
      name: "Wine Bar",
      category: "shop",
      subType: "tavern",
      x: 6200,
      y: 2700,
      width: 50,
      height: 40,
      maxOwners: 10,
      basePrice: 5000,
      baseIncome: 100,
      notes: "Premium drinks, +mood buff",
    },
    {
      name: "Artisan Workshop",
      category: "shop",
      subType: "general_store",
      x: 6200,
      y: 3100,
      width: 60,
      height: 50,
      maxOwners: 10,
      basePrice: 6000,
      baseIncome: 120,
      notes: "Handcrafted goods, furniture",
    },
    {
      name: "Traditional Restaurant",
      category: "shop",
      subType: "inn",
      x: 5100,
      y: 3400,
      width: 60,
      height: 50,
      maxOwners: 15,
      basePrice: 7000,
      baseIncome: 140,
      notes: "Unique meals, rare recipes",
    },
    {
      name: "Inn & Tavern",
      category: "shop",
      subType: "inn",
      x: 5500,
      y: 3400,
      width: 80,
      height: 60,
      maxOwners: 15,
      basePrice: 8000,
      baseIncome: 160,
      notes: "Rest, quests, gossip",
    },
  ],
  roads: [
    {
      name: "Main Street",
      x1: 5000,
      y1: 2000,
      x2: 6800,
      y2: 2000,
      style: "cobblestone",
    },
    {
      name: "Market Lane",
      x1: 5000,
      y1: 2550,
      x2: 6800,
      y2: 2550,
      style: "cobblestone",
    },
    {
      name: "Central Avenue",
      x1: 5900,
      y1: 1500,
      x2: 5900,
      y2: 3500,
      style: "cobblestone",
    },
  ],
  decorations: [
    {
      name: "Town Square",
      type: "square",
      x: 5100,
      y: 2600,
      width: 400,
      height: 300,
    },
    {
      name: "Fountain Plaza",
      type: "fountain",
      x: 5300,
      y: 2800,
      width: 80,
      height: 60,
    },
    { name: "Well", type: "well", x: 6400, y: 3450, width: 20, height: 20 },
  ],
};

export default oldtown;
