// convex/map/zones/suburbs.ts
// Zone 7: Suburbs (600,3200 → 3200,5800)
// 2600×2600 — Quiet residential neighborhoods with a school, church, local shops.

import type { ZoneData } from "./types";

const suburbs: ZoneData = {
  id: "suburbs",
  buildings: [
    // ── Elm Street Houses ──
    {
      name: "House #1",
      category: "residential",
      subType: "house",
      x: 700,
      y: 3400,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "House #2",
      category: "residential",
      subType: "house",
      x: 900,
      y: 3400,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "House #3",
      category: "residential",
      subType: "house",
      x: 1100,
      y: 3400,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "House #4",
      category: "residential",
      subType: "house",
      x: 1300,
      y: 3400,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "House #5",
      category: "residential",
      subType: "house",
      x: 1500,
      y: 3400,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "Duplex #1",
      category: "residential",
      subType: "duplex",
      x: 2400,
      y: 3400,
      width: 60,
      height: 50,
      maxOwners: 8,
      basePrice: 2000,
      baseIncome: 30,
    },
    {
      name: "House #6",
      category: "residential",
      subType: "house",
      x: 2900,
      y: 3400,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },

    // ── Maple Avenue ──
    {
      name: "House #7",
      category: "residential",
      subType: "house",
      x: 700,
      y: 3850,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "House #8",
      category: "residential",
      subType: "house",
      x: 900,
      y: 3850,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "Apartment Block A",
      category: "residential",
      subType: "apartment",
      x: 1200,
      y: 3850,
      width: 80,
      height: 60,
      maxOwners: 20,
      basePrice: 3500,
      baseIncome: 50,
    },
    {
      name: "House #9",
      category: "residential",
      subType: "house",
      x: 2500,
      y: 3850,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "House #10",
      category: "residential",
      subType: "house",
      x: 2700,
      y: 3850,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },

    // ── Oak Drive ──
    {
      name: "House #11",
      category: "residential",
      subType: "house",
      x: 1000,
      y: 4350,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "House #12",
      category: "residential",
      subType: "house",
      x: 2300,
      y: 4350,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "Apartment Block B",
      category: "residential",
      subType: "apartment",
      x: 2800,
      y: 4400,
      width: 80,
      height: 60,
      maxOwners: 20,
      basePrice: 3500,
      baseIncome: 50,
    },

    // ── Cedar Lane ──
    {
      name: "House #13",
      category: "residential",
      subType: "house",
      x: 700,
      y: 4850,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "House #14",
      category: "residential",
      subType: "house",
      x: 900,
      y: 4850,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "House #15",
      category: "residential",
      subType: "house",
      x: 1100,
      y: 4850,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "House #16",
      category: "residential",
      subType: "house",
      x: 2100,
      y: 4850,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "House #17",
      category: "residential",
      subType: "house",
      x: 2300,
      y: 4850,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "House #18",
      category: "residential",
      subType: "house",
      x: 2500,
      y: 4850,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },

    // ── Birch Road ──
    {
      name: "House #19",
      category: "residential",
      subType: "house",
      x: 1000,
      y: 5350,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "Duplex #2",
      category: "residential",
      subType: "duplex",
      x: 1400,
      y: 5350,
      width: 60,
      height: 50,
      maxOwners: 8,
      basePrice: 2000,
      baseIncome: 30,
    },
    {
      name: "House #20",
      category: "residential",
      subType: "house",
      x: 2200,
      y: 5350,
      width: 50,
      height: 50,
      maxOwners: 5,
      basePrice: 1000,
      baseIncome: 10,
    },
    {
      name: "Apartment Block C",
      category: "residential",
      subType: "apartment",
      x: 2800,
      y: 5350,
      width: 80,
      height: 60,
      maxOwners: 20,
      basePrice: 3500,
      baseIncome: 50,
    },

    // ── Service ──
    {
      name: "Community Center",
      category: "service",
      subType: "community_center",
      x: 2200,
      y: 3850,
      width: 80,
      height: 60,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Local events, notice board, meetups",
    },
    {
      name: "School",
      category: "service",
      subType: "school",
      x: 1600,
      y: 4400,
      width: 120,
      height: 80,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Education, tutoring quests",
    },
    {
      name: "Church",
      category: "service",
      subType: "church",
      x: 1800,
      y: 4850,
      width: 80,
      height: 80,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Events, weddings, community",
    },
    {
      name: "Clinic",
      category: "service",
      subType: "clinic",
      x: 2200,
      y: 5350,
      width: 60,
      height: 50,
      maxOwners: 0,
      basePrice: 0,
      baseIncome: 0,
      notes: "Healing, medical quests",
    },

    // ── Shops ──
    {
      name: "Grocery Store",
      category: "shop",
      subType: "grocery_store",
      x: 700,
      y: 4300,
      width: 60,
      height: 50,
      maxOwners: 15,
      basePrice: 3000,
      baseIncome: 80,
      notes: "Daily food, produce from farms",
    },
    {
      name: "Hardware Store",
      category: "shop",
      subType: "hardware_store",
      x: 700,
      y: 5350,
      width: 60,
      height: 50,
      maxOwners: 10,
      basePrice: 4000,
      baseIncome: 100,
      notes: "Tools, building supplies, axes",
    },
  ],
  roads: [
    {
      name: "Elm Street",
      x1: 600,
      y1: 3300,
      x2: 3200,
      y2: 3300,
      style: "residential",
    },
    {
      name: "Maple Avenue",
      x1: 600,
      y1: 3750,
      x2: 3200,
      y2: 3750,
      style: "residential",
    },
    {
      name: "Oak Drive",
      x1: 600,
      y1: 4200,
      x2: 3200,
      y2: 4200,
      style: "residential",
    },
    {
      name: "Cedar Lane",
      x1: 600,
      y1: 4750,
      x2: 3200,
      y2: 4750,
      style: "residential",
    },
    {
      name: "Birch Road",
      x1: 600,
      y1: 5250,
      x2: 3200,
      y2: 5250,
      style: "residential",
    },
    {
      name: "West Side",
      x1: 600,
      y1: 3200,
      x2: 600,
      y2: 5800,
      style: "residential",
    },
    {
      name: "East Side",
      x1: 3200,
      y1: 3200,
      x2: 3200,
      y2: 5800,
      style: "residential",
    },
  ],
  decorations: [],
};

export default suburbs;
